version: '3.3'

services:

  db:
    image: postgres-es
    build: postgres-es
    environment:
        - POSTGRES_PASSWORD=secreto
        - POSTGRES_USER=dbuser 
        - POSTGRES_DB=db
    ports:
      - "5432:5432"

  catalogo:
    build: catalogo
    depends_on:
      - db
    image: catalogo:latest
    working_dir: /local/app
    env_file:
      - .env.catalogo
    volumes:
      - ./catalogo/app:/local/app
    ports:
      - "80:5000"
